"""add column color to product table

Revision ID: 3cad5335e5d1
Revises: 3237e8a37d39
Create Date: 2026-06-21 15:55:05.570071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cad5335e5d1'
down_revision: Union[str, Sequence[str], None] = '3237e8a37d39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('color', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'color')
    # ### end Alembic commands ###
